### ISSUE TITLE
.alfredworkflow

### ISSUE THREAD

**Issue by ghost** [alanzchen/zotero-better-bibtex-alfred#1]
How can I actually install it, since it is not an _.alfredworkflow_ file?

**Comment by alanzchen** [comment]
Clone this project, rename the folder to `zotero-better-bibtex-alfred.alfredworkflow`.

**Comment by ghost** [comment]
OK, I did that and have it installed.

Unfortunately, it doesn't work for me. Should I do something else besides installing it?

**Comment by alanzchen** [comment]
Do you have the Better Bibtex Zotero plugin installed? And can you provide the debug message in your Alfred?

https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by ghost** [comment]
I got help here www.alfredforum.com/topic/12667-how-i-convert-a-folder-with-a-workflow-into-alfredworkflow/

It had to install requests.

It works now – most of the time. For some entries in Zotero I don’t get results in your workflow.
Am 14. Mai 2019, 20:18 +0300 schrieb Alan Chen <notifications@github.com>:
